// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Management struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Zip     string `json:"zip"`
	Address string `json:"address"`
}

type Manager struct {
	ID            string `json:"id"`
	Email         string `json:"email"`
	FirstName     string `json:"firstName"`
	LastName      string `json:"lastName"`
	ManagemnetsID int    `json:"managemnetsID"`
}

type NewManager struct {
	Email         string `json:"email"`
	FirstName     string `json:"firstName"`
	LastName      string `json:"lastName"`
	ManagemnetsID int    `json:"managemnetsID"`
}
